### PR TITLE
♻️ Update ERC1155 loop counters

### PR DESCRIPTION
**Pull request by z0r0z**
optimize for loops

### CODE REVIEW

**Comment by z0r0z** [comment]
I will get a waifu before this test finishes running

**Comment by transmissions11** [comment]
lmeow

**Comment by transmissions11** [comment]
huh this doesn't seem to save any gas according to `dapp`, but will merge anyway so i dont have to deal with future optimizoooors spamming me with prs to do this anyways

**Comment by z0r0z** [comment]
is this winning anons

**Pull request merged**
