### PR TITLE
⚡️ Optimize ERC721 jumps

### PR DESCRIPTION
**Pull request by wilsoncusack**
## Description

Rather than putting `to.code.length == 0` in a `OR` conditional in the require, we can optimize by pulling this out of the require and wrapping the require in `if (to.code.length != 0)`

## Checklist

Ensure you completed **all of the steps** below before submitting your pull request:

- [ ] Ran `dapp snapshot`?
- [ ] Ran `npm run lint`?
- [ ] Ran `forge test`?
- [ ] Ran `dapp test`?

_Pull requests with an incomplete checklist will be thrown out._
lol ok but I don't have Dapp setup on my computer

### CODE REVIEW

**Comment by wilsoncusack** [comment]
Going to close this because I can't perform the check list, but it's here if you want it!

**Comment by transmissions11** [comment]
haha ill be removing dapp support entirely soon

**Comment by transmissions11** [comment]
lol its a bit upsetting this saves gas

**Comment by transmissions11** [comment]
but i know why... using an or is dumb here cuz it basically gets turned into two adjacent ifs

if we used && i think that would achieve the same effect

**Pull request merged**
