### PR TITLE
Bytes32AddressLib Save Gas

### PR DESCRIPTION
**Pull request by itsdevbear**
## Description
Save some gas by utilizing the free memory pointer space (which will be zero'd out) to just directly load the calldata and then return it as is.

## Checklist

Ensure you completed **all of the steps** below before submitting your pull request:

- [x] Ran `forge snapshot`?
- [x] Ran `npm run lint`?
- [x] Ran `forge test`?

_Pull requests with an incomplete checklist will be thrown out._

### CODE REVIEW

**Comment by transmissions11** [comment]
this is an internal function, the inputs are not guaranteed to be in calldata at all, let alone at those specific offsets?

**Comment by transmissions11** [comment]
also using the return statement in yul does not return from the local callframe, it ends the top level call entirely (like reverting)

**Comment by itsdevbear** [comment]
Oh 100% facts, was too on autopilot

**Comment by transmissions11** [comment]
hehe

**Pull request closed without merging**
