### PR TITLE
✨ ERC721

### PR DESCRIPTION
**Pull request by distractedm1nd**
Reposting from suggestion in #63: 

Hey, the tests were not running at all, not only because they were set to symbolic execution, but also because much of the ERC20 logic wasn't correctly mapped onto ERC721. Now they work, but I'm not sure if they are adequate to pull into the main branch. I still have some concerns that I wanted to look into over the weekend, mainly about the effects of transfers to address(0).

Also, I changed the tokenURI functionality to match what most projects use today - concatenating a url to a tokenID. This saves us the massive storage that the map would have taken up and just gives us a view function that whatever frontend calls to resolve the metadata

### CODE REVIEW

**Review by z0r0z — COMMENTED** [review]
this is awesome, and appreciate wrestling through tests.

I hesitate to make tokenURI opinionated to baseURI format, as those tend to be references to centralized dbs? I would also vertically stack the vars in constructor, and make vars in `_mint` horizontal to fit style.

**Comment by distractedm1nd** [comment]
Thanks!

is not a reference to a centralized db, because most (legit) projects upload a folder to IPFS - then it works just as intended. `ipfs://hashOfEntireFolderContents/1` would resolve correctly for example. BUT I noticed a problem: I am not using something like `Strings for uint256`, so concatting like that won't work - going to fix

Also thanks for the heads up about the constructor, didn't notice

**Comment by alephao** [comment]
So the `transferFrom` tests were failing for some cases, I remade them, can you guys have a look?  https://github.com/distractedm1nd/solmate/pull/1/files

Also added test two edge cases: minting token with same id and burning inexistent tokens

I feel there are still a bunch of non-happy path tests missing, will try looking further when I get some more time

**Comment by alephao** [comment]
> I hesitate to make tokenURI opinionated to baseURI format, as those tend to be references to centralized dbs?

What do you suggest? The only alternative I can think of right now is to make the contract abstract with an empty implementation of the `tokenURI` method, thoughts?

**Comment by distractedm1nd** [comment]
[Directories on IPFS are just as immutable as single files](https://medium.com/infinitism/erc-4337-account-abstraction-without-ethereum-protocol-changes-d75c9d94dc4a). How would this be centralized?

**Comment by transmissions11** [comment]
can you take this out of draft i'll merge into `audit-fixes` and productionize from there thank you all for your great work ❤️

**Comment by transmissions11** [comment]
oh woah i can do that myself nice

**Pull request merged**
