### PR TITLE
✨ V6: First Production Release

### PR DESCRIPTION
**Pull request by transmissions11**

### CODE REVIEW

**Comment by transmissions11** [comment]
bound() does not satisfy its core invariants 

`bound(0, 68, 69) = 70`
`bound(0, 115792089237316195423570985008687907853269984665640564039457584007913129639654, 115792089237316195423570985008687907853269984665640564039457584007913129639678) = 115792089237316195423570985008687907853269984665640564039457584007913129639675`

**Comment by transmissions11** [comment]
> bound() does not satisfy its core invariants

i think i fixed this in the commit right above

**Comment by transmissions11** [comment]
is permit a thing that goes in 721 and 1155? gotta do some research

**Comment by distractedm1nd** [comment]
generally no, it's nice to have but it's not typical and the vast majority of projects would never use, especially cause most nft projects are on l1 where relaying wouldn't be a thing anyways

including it would depend I guess on what solmate is trying to be?

**Comment by transmissions11** [comment]
ok im not gonna include it cuz seems like there's diverging ideas on how it should be impl'd (uni uses some weird draft eip in theirs)

**Pull request merged**
