### PR TITLE
[ERC721] Delete approved if have

### PR DESCRIPTION
**Pull request by rotcivegaf**
## Description

Clear `getApproved` only if have an approved address

Statistically, this would save gas, the sum of an `owner` transfer and `isApprovedForAll` transfer is greater than an `approved` transfer

Save 80 gas if the `getApproved` haven't a approved
Spend 150 gas if the `getApproved` have a approved
_(In each `transferFrom`, according to my tests)_

## Checklist

Ensure you completed **all of the steps** below before submitting your pull request:

- [X] Ran `forge snapshot`?
- [X] Ran `npm run lint`?
- [X] Ran `forge test`?

_Pull requests with an incomplete checklist will be thrown out._

### CODE REVIEW

**Comment by rotcivegaf** [comment]
What do you think about:
 - Emitting the `Approval` event if the approved is cleared?
 - Use the same pattern in the `_burn` function

**Comment by transmissions11** [comment]
uh ser i dont see any changes in the diff... and you've installed solmate... in solmate?

**Comment by transmissions11** [comment]
i'd like to see the diffs before i comment on those changes (im a codecel lol i cant think in human terms)

**Comment by Vectorized** [comment]
This actually does work. But the code is missing.

**Comment by rotcivegaf** [comment]
Sorry, I needed to sleep, I forgot push the change...
Check #255 PR

**Pull request closed without merging**
