### PR TITLE
fix(solidity): avoid && logic in req. statements

### PR DESCRIPTION
**Pull request by sambacha**
Avoid && logic in require statements

Can gas golf to show benefit if needed

### CODE REVIEW

**Comment by transmissions11** [comment]
yeah i know about this optimization (why solc???? why...) but i dont think the gas savings are worth the readability savings

**Comment by sambacha** [comment]
> thanks for the PR!
> 
> 
> 
> i've seen this optimization before (why solc???? why...) but i dont think the gas savings are worth the readability cost

Wait, you think this is less readable?

**Comment by sambacha** [comment]
> thanks for the PR!
> 
> 
> 
> i've seen this optimization before (why solc???? why...) but i dont think the gas savings are worth the readability cost

Either way thanks for the response, cheers

**Comment by z0r0z** [comment]
can't we avoid this double check regardless by only doing `require(recoveredAddress == owner)`?

is `!= address(0)` doing any work? For example, as I understand, address(0) is recovered if things fail on invalid signature. This gets scooped into == owner check? And if UI messes up and puts address(0) in as the owner, there would be no valid signature, and the same thing will happen anyways?

**Pull request closed without merging**
